version: "3"
services:
  app:
    image: guizo/docker-php-apache
    ports:
      - 8084:80
    volumes:
      - ./app:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
  db:
    image: mysql:5.7
    ports:
      - 33064:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=quizit
      - MYSQL_ROOT_PASSWORD=root
volumes:
  db_data:
    driver: local
